### PR TITLE
dragify.js

### PR DESCRIPTION
**Pull request by tiziana89**
I have add a new listener for touchend touchstart and touchmove since is not working with chrome on toichscreen :)

### CODE REVIEW

**Comment by tiziana89** [comment]
In chrome touchscreen is not working

**Comment by hawkerboy7** [comment]
Hi tiziana89!
This pull request only applies the changes to the distribution file, not the souce.
I will add this to the source as well.

**Comment by tiziana89** [comment]
Hi Dexter,
Could you let me know when is done so I can update the library on taskboard
:P Thanks!!


2017-06-19 13:56 GMT+02:00 Dexter Esajas <notifications@github.com>:

**Comment by hawkerboy7** [comment]
Hi @tiziana89, I just had a quick test to see if I could add it easily. The touchstart, touchend and touchdrag events are different from the mouse events. They seem to miss some data so it won't be a quick fix I am afraid.. :( I'll try to get some more time available to support mobile as well.

**Comment by hawkerboy7** [comment]
@tiziana89 You could also use [Dragula](https://github.com/bevacqua/dragula) in the mean time! They do support mobile! However they lack the hardware acceleration, threshold and transition support.

**Pull request closed without merging**
